version: '3.7'

services:
  taskbot:
    image: kleptsov/task_bot
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - TASK_BOT
      - ADMIN_ID
    container_name: task_bot_compose
    restart: always
#     volumes:
#       - db:/home/appuser/task_bot/data
# volumes:
#   db: